package factorio.object.types;

import com.google.gson.annotations.SerializedName;

public enum VirtualSignal implements TypeInterface {
    // Special
    @SerializedName("signal-each") EACH,
    @SerializedName("signal-everything") EVERYTHING,
    @SerializedName("signal-anything") ANYTHING,
    // Numbers
    @SerializedName("signal-0") ZERO,
    @SerializedName("signal-1") ONE,
    @SerializedName("signal-2") TWO,
    @SerializedName("signal-3") THREE,
    @SerializedName("signal-4") FOUR,
    @SerializedName("signal-5") FIVE,
    @SerializedName("signal-6") SIX,
    @SerializedName("signal-7") SEVEN,
    @SerializedName("signal-8") EIGHT,
    @SerializedName("signal-9") NINE,
    // Letters
    @SerializedName("signal-A") A,
    @SerializedName("signal-B") B,
    @SerializedName("signal-C") C,
    @SerializedName("signal-D") D,
    @SerializedName("signal-E") E,
    @SerializedName("signal-F") F,
    @SerializedName("signal-G") G,
    @SerializedName("signal-H") H,
    @SerializedName("signal-I") I,
    @SerializedName("signal-J") J,
    @SerializedName("signal-K") K,
    @SerializedName("signal-L") L,
    @SerializedName("signal-M") M,
    @SerializedName("signal-N") N,
    @SerializedName("signal-O") O,
    @SerializedName("signal-P") P,
    @SerializedName("signal-Q") Q,
    @SerializedName("signal-R") R,
    @SerializedName("signal-S") S,
    @SerializedName("signal-T") T,
    @SerializedName("signal-U") U,
    @SerializedName("signal-V") V,
    @SerializedName("signal-W") W,
    @SerializedName("signal-X") X,
    @SerializedName("signal-Y") Y,
    @SerializedName("signal-Z") Z,
    // Colors
    @SerializedName("signal-red") RED,
    @SerializedName("signal-green") GREEN,
    @SerializedName("signal-blue") BLUE,
    @SerializedName("signal-yellow") YELLOW,
    @SerializedName("signal-pink") PINK,
    @SerializedName("signal-cyan") CYAN,
    @SerializedName("signal-white") WHITE,
    @SerializedName("signal-grey") GREY,
    @SerializedName("signal-black") BLACK,
    // Miscellaneous
    @SerializedName("signal-check") CHECK,
    @SerializedName("signal-deny") DENY,
    @SerializedName("signal-info") INFO,
    @SerializedName("signal-dot") DOT,
    // Shapes
    @SerializedName("shape-vertical") SHAPE_VERTICAL,
    @SerializedName("shape-horizontal") SHAPE_HORIZONTAL,
    @SerializedName("shape-diagonal") SHAPE_DIAGONAL,
    @SerializedName("shape-curve") SHAPE_CURVE,
    @SerializedName("shape-cross") SHAPE_CROSS,
    @SerializedName("shape-diagonal-cross") SHAPE_DIAGONAL_CROSS,
    @SerializedName("shape-corner") SHAPE_CORNER,
    @SerializedName("shape-t") SHAPE_T,
    @SerializedName("shape-circle") SHAPE_CIRCLE,
    // Arrows
    @SerializedName("up-arrow") UP_ARROW,
    @SerializedName("up-right-arrow") UP_RIGHT_ARROW,
    @SerializedName("right-arrow") RIGHT_ARROW,
    @SerializedName("down-right-arrow") DOWN_RIGHT_ARROW,
    @SerializedName("down-arrow") DOWN_ARROW,
    @SerializedName("down-left-arrow") DOWN_LEFT_ARROW,
    @SerializedName("left-arrow") LEFT_ARROW,
    @SerializedName("up-left-arrow") UP_LEFT_ARROW,
    // Additions
    @SerializedName("signal-stack-size") STACK_SIZE,
    @SerializedName("signal-heart") HEART,
    @SerializedName("signal-skull") SKULL,
    @SerializedName("signal-ghost") GHOST,
    // Parameters
    @SerializedName("signal-signal-parameter") SIGNAL_PARAMETER,
    @SerializedName("signal-item-parameter") ITEM_PARAMETER,
    @SerializedName("signal-fluid-parameter") FLUID_PARAMETER,
    @SerializedName("signal-fuel-parameter") FUEL_PARAMETER,
    // Unknown
    @SerializedName("signal-unknown") UNKNOWN;
    @Override
    public Type getType() {
        return Type.VIRTUAL;
    }
}
